MODEL:
  NUM_CLASSES: 5
  BACKBONE:
    NAME: 'efficient_net-b3'
    OUT_CHANNELS: (48, 136, 384, 256, 256, 256)
    PRETRAINED: True
  PRIORS:
    FEATURE_MAPS: [ [38, 38], [19, 19], [10, 10], [5, 5], [3, 3], [1, 1]]
    #FEATURE_MAPS: [ [40, 30], [20, 15], [10, 8], [5, 4], [3, 2], [1, 1]]
INPUT:
  IMAGE_SIZE: [300, 300]
  #IMAGE_SIZE: [320, 240]
DATASETS:
  TRAIN: ("tdt4265_train",)
  TEST: ("tdt4265_val", )
SOLVER:
  MAX_ITER: 160_000
  LR_STEPS: [105_000, 135_000]
  GAMMA: 0.1
  BATCH_SIZE: 16
  LR: 1e-3
DATA_LOADER:
  NUM_WORKERS: 4
OUTPUT_DIR: 'outputs/basic'
DATASET_DIR: "datasets"