MODEL:
    NUM_CLASSES: 5
    BACKBONE:
        NAME: 'basicres'
        PRETRAINED: False
        OUT_CHANNELS: [256, 256, 512, 256, 256, 128]
        INPUT_CHANNELS: 3
    #PRIORS:
    #    FEATURE_MAPS: [ 38, 19, 10, 5, 3, 1]
    #    STRIDES: [8, 16, 32, 64, 100, 300]
    #    MIN_SIZES: [30, 60, 111, 162, 213, 264]
    #    MAX_SIZES: [60, 111, 162, 213, 264, 315]
    #    ASPECT_RATIOS: [[2, 3], [2, 3], [2, 3], [2, 3], [2], [2]]
    #    # When has 1 aspect ratio, every location has 4 boxes, 2 ratio 6 boxes.
    #    # #boxes = 2 + #ratio * 2
    #    BOXES_PER_LOCATION: [ 6, 6, 6, 6, 4, 4]  # number of boxes per feature map location
INPUT:
    IMAGE_SIZE: 300
DATASETS:
    TRAIN: ("waymo_train",)
    TEST: ("waymo_val", )
SOLVER:
    MAX_ITER: 10_000
    LR_STEPS: [80000, 100000]
    GAMMA: 0.1
    BATCH_SIZE: 16
    LR: 1e-3
OUTPUT_DIR: 'outputs/basic'
DATASET_DIR: "datasets"