MODEL:
    NUM_CLASSES: 5
    BACKBONE:
        NAME: 'inception'
        PRETRAINED: True
        OUT_CHANNELS: [256, 768, 768, 1280, 2048, 2048]
        INPUT_CHANNELS: 3
    PRIORS:
        FEATURE_MAPS: [35, 17, 17, 8, 8, 1]
INPUT:
    IMAGE_SIZE: 299 # 300
DATASETS:
    TRAIN: ("tdt4265_train",)
    TEST: ("tdt4265_val", )
SOLVER:
    MAX_ITER: 25000
    LR_STEPS: [80000, 100000]
    GAMMA: 0.1
    BATCH_SIZE: 32
    LR: 1e-3
EVAL_STEP: 2000
MODEL_SAVE_STEP: 2000
OUTPUT_DIR: 'outputs/inception'
DATASET_DIR: "datasets"