MODEL:
    NUM_CLASSES: 5
INPUT:
    IMAGE_SIZE: 300
DATASETS:
    TRAIN: ("tdt4265_train",)
    TEST: ("tdt4265_val", )
SOLVER:
    MAX_ITER: 5000
    LR_STEPS: [80000, 100000]
    GAMMA: 0.1
    BATCH_SIZE: 8
    LR: 5e-4
  
OUTPUT_DIR: 'outputs/vgg_TDT'
EVAL_STEP: 2500
MODEL_SAVE_STEP: 2500
DATASET_DIR: "datasets/"