MODEL:
    NUM_CLASSES: 5
    BACKBONE:
        NAME: 'resnet_50'
        # NAME: 'vgg'
        # NAME: 'alex_net'
        PRETRAINED: True
        OUT_CHANNELS: [512, 1024, 512, 256, 256, 256]
        OUT_CHANNELS: [64, 64, 128, 128, 256, 256]
        # OUT_CHANNELS: [128, 256, 128, 128, 64, 64]
        # OUT_CHANNELS: [256, 512, 256, 256, 128, 128]
        INPUT_CHANNELS: 3
INPUT:
    IMAGE_SIZE: 300
    # IMAGE_SIZE: 224
DATASETS:
    TRAIN: ("waymo_train",)
    TEST: ("waymo_val", )
SOLVER:
    MAX_ITER: 10_000
    LR_STEPS: [80000, 100000]
    GAMMA: 0.1
    BATCH_SIZE: 16
    LR: 1e-3
OUTPUT_DIR: 'outputs/resnet50_test'
DATASET_DIR: "datasets"
