MODEL:
    NUM_CLASSES: 5
    BACKBONE:
        NAME: 'basic'
        PRETRAINED: False
        OUT_CHANNELS: [256, 512, 256, 256, 128, 128]
        INPUT_CHANNELS: 3
    PRIORS:
        #FEATURE_MAPS: [ [38, 38], [19, 19], [10, 10], [5, 5], [3, 3], [1, 1]]
        FEATURE_MAPS: [ [30, 40], [15, 20], [8, 10], [4, 5], [2, 3], [1, 1] ]
INPUT:
    #IMAGE_SIZE: [300, 300]
    IMAGE_SIZE: [320, 240]
DATASETS:
    TRAIN: ("waymo_train",)
    TEST: ("waymo_val", )
SOLVER:
    MAX_ITER: 10_000
    LR_STEPS: [80_000, 100_000]
    GAMMA: 0.1
    BATCH_SIZE: 16
    LR: 1e-3
OUTPUT_DIR: 'outputs/basic'
DATASET_DIR: "datasets"